### ISSUE TITLE
[FEAT]: Icon Color

### ISSUE THREAD

**Issue by Angel-Ponce** [shinokada/svelte-ionicons#1]
### Description

Is there any way to build something like:

```svelte 
<SomeIcon size="30" class="text-red-200" />
``` 

To render `SomeIcon` on red color?

**Comment by shinokada** [comment]
Hi,
The first version was able to add color, then I realized that icons were not meant with colors. They looked terrible!
So change them without color.
Please find other icons from https://svelte-svg-icons.vercel.app/

**Comment by shinokada** [comment]
I just added colors.
