### ISSUE TITLE
[FEAT]: Remove ionicon title tag

### ISSUE THREAD

**Issue by Angel-Ponce** [shinokada/svelte-ionicons#5]
### Description

![image](https://user-images.githubusercontent.com/60164099/226990331-168ca3a0-2328-409b-9ec8-7d18d38fecd6.png)

As you can see the components have a `<title></title>` tag
When the mouse hover the icon the title appears, and, i think that this value should be editable or removable.

**Comment by shinokada** [comment]
Which icon are you talking about?

**Comment by Angel-Ponce** [comment]
> Which icon are you talking about?

Every one

**Comment by shinokada** [comment]
Where in this [file](https://raw.githubusercontent.com/shinokada/svelte-ionicons/main/src/lib/Accessibility.svelte) has title?

**Comment by Angel-Ponce** [comment]
I cant see anything, but, try to render the `Pencil` ionicon imported as

```js
import { Pencil } from "svelte-ionicons"
```

and see the html output of this:

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="min-width: 16px; min-height: 16px; max-width: 16px; max-height: 16px;" class="" width="16" height="16" fill="currentColor"><title>ionicons-v5-k</title><polygon points="358.62 129.28 86.49 402.08 70 442 109.92 425.51 382.72 153.38 358.62 129.28" style="fill: none; stroke: currentcolor; stroke-linecap: round; stroke-linejoin: round; stroke-width: 44px;"></polygon><path d="M413.07,74.84,401.28,86.62l24.1,24.1,11.79-11.79a16.51,16.51,0,0,0,0-23.34l-.75-.75A16.51,16.51,0,0,0,413.07,74.84Z" style="fill: none; stroke: currentcolor; stroke-linecap: round; stroke-linejoin: round; stroke-width: 44px;"></path></svg>
```

As you can see, the <title></title> tag appears automatically

**Comment by shinokada** [comment]
See this [REPL](https://svelte.dev/repl/fef5555de8264d6fbea7f7747a473ea6?version=3.57.0). There is no title tag.

It could be your set up or other library is adding it.

**Comment by Angel-Ponce** [comment]
Oh :c I understand, Im sorry for your time, and tanks for your help.
